### ISSUE TITLE
Wrap translated text in Fragment instead of <span>

### ISSUE THREAD

**Issue by rynocouse** [fusionjs/fusion-plugin-i18n-react#142]
Currently the Translate component wraps around the translation `<span>Bonjour</span>` by default. Has any thought been given to using a React `<Fragment>` in instead of forcing the extra markup?

https://github.com/fusionjs/fusion-plugin-i18n-react/blob/aacf2ff67044d7fdc44be66dbe6f2382e1867e3a/src/translate.js#L25-L28

### Type of issue

Enhancement

**Comment by mlmorg** [comment]
Do you want to PR this?
