### ISSUE TITLE
withTranslations overwrites its child's context

### ISSUE THREAD

**Issue by phou87** [fusionjs/fusion-plugin-i18n-react#176]
Due to [this line](https://github.com/fusionjs/fusion-plugin-i18n-react/blob/master/src/with-translations.js#L43), the component that withTranslations wraps loses its context. This is very harmful when used in conjunction with plugins such as fusion-plugin-rpc-redux-react (HOC's created by withRPCRedux rely on context.store to be defined, and it doesn't check for it, resulting in a delayed error).

**Comment by rtsao** [comment]
This was fixed in https://github.com/fusionjs/fusion-plugin-i18n-react/pull/175 and released in v1.1.1
