### ISSUE TITLE
Client side translations broken in 1.2.0-1

### ISSUE THREAD

**Issue by brendean** [fusionjs/fusion-plugin-i18n-react#188]
### Type of issue

Bug

### Description

After upgrading from 1.1.1-1 to 1.2.1-0 translated strings are not loaded in the browser, instead the keys are displayed.

### Current behavior

Translated strings not shown on client

### Expected behavior

Translated strings shown on client

### Your environment

* fusion-plugin-i18n-react version: 1.2.1-0

* Node.js version (`node --version`): v8.11.3

**Comment by KevinGrandon** [comment]
Possibly due to https://github.com/fusionjs/fusion-plugin-i18n-react/pull/184?

**Comment by rtsao** [comment]
This was due to duplicate i18n packages in the node_module tree.
